// Generated by scripts/fetch_creature_stats.py — do not edit by hand.
// Sources: OSRS Wiki infobox_monster + money_making_guide buckets.
const STATS = [
  {
    "name": "Crawling Hands",
    "slayerXp": 19,
    "hp": 19,
    "superior": "Crushing hand",
    "superiorXp": 550,
    "kph": null,
    "kphSource": null,
    "kphNote": null
  },
  {
    "name": "Cave Crawlers",
    "slayerXp": 22,
    "hp": 22,
    "superior": "Chasm crawler",
    "superiorXp": 600,
    "kph": null,
    "kphSource": null,
    "kphNote": null
  },
  {
    "name": "Banshees",
    "slayerXp": 22,
    "hp": 22,
    "superior": "Screaming banshee",
    "superiorXp": 610,
    "kph": null,
    "kphSource": null,
    "kphNote": null
  },
  {
    "name": "Rockslugs",
    "slayerXp": 27,
    "hp": 27,
    "superior": null,
    "superiorXp": null,
    "kph": null,
    "kphSource": null,
    "kphNote": null
  },
  {
    "name": "Cockatrice",
    "slayerXp": 37,
    "hp": 37,
    "superior": "Cockathrice",
    "superiorXp": 950,
    "kph": null,
    "kphSource": null,
    "kphNote": null
  },
  {
    "name": "Pyrefiends",
    "slayerXp": 45,
    "hp": 45,
    "superior": "Flaming pyrelord",
    "superiorXp": 1250,
    "kph": null,
    "kphSource": null,
    "kphNote": null
  },
  {
    "name": "Infernal Mages",
    "slayerXp": 60,
    "hp": 60,
    "superior": "Malevolent mage",
    "superiorXp": 1750,
    "kph": null,
    "kphSource": null,
    "kphNote": null
  },
  {
    "name": "Bloodveld",
    "slayerXp": 134,
    "hp": 134,
    "superior": "Insatiable Bloodveld",
    "superiorXp": 2900,
    "kph": 746,
    "kphSource": "Slayer training: 100,000 XP/h (Cannon and Venator Bow)",
    "kphNote": "derived from XP/h using Cannon and Venator Bow"
  },
  {
    "name": "Gryphons",
    "slayerXp": 110,
    "hp": 110,
    "superior": "Dire gryphon",
    "superiorXp": 2800,
    "kph": 455,
    "kphSource": "Slayer training: 50,000 XP/h",
    "kphNote": "derived from XP/h"
  },
  {
    "name": "Jellies",
    "slayerXp": 75,
    "hp": 75,
    "superior": "Vitreous jelly",
    "superiorXp": 1900,
    "kph": null,
    "kphSource": null,
    "kphNote": null
  },
  {
    "name": "Custodian Stalkers",
    "slayerXp": null,
    "hp": null,
    "superior": null,
    "superiorXp": null,
    "kph": null,
    "kphSource": null,
    "kphNote": null
  },
  {
    "name": "Turoth",
    "slayerXp": 81,
    "hp": 81,
    "superior": "Spiked turoth",
    "superiorXp": 1998,
    "kph": null,
    "kphSource": null,
    "kphNote": null
  },
  {
    "name": "Warped Creatures",
    "slayerXp": 200,
    "hp": 200,
    "superior": "Mutated terrorbird",
    "superiorXp": 3200,
    "kph": 275,
    "kphSource": "Slayer training: 55,000 XP/h (Cannon)",
    "kphNote": "derived from XP/h using Cannon"
  },
  {
    "name": "Cave Horrors",
    "slayerXp": 55,
    "hp": 55,
    "superior": "Cave abomination",
    "superiorXp": 1300,
    "kph": 300,
    "kphSource": "money making guide: Killing cave horrors",
    "kphNote": null
  },
  {
    "name": "Aberrant Spectres",
    "slayerXp": 90,
    "hp": 90,
    "superior": "Abhorrent spectre",
    "superiorXp": 2500,
    "kph": 389,
    "kphSource": "Slayer training: 35,000 XP/h",
    "kphNote": "derived from XP/h"
  },
  {
    "name": "Basilisks",
    "slayerXp": 75,
    "hp": 75,
    "superior": "Monstrous basilisk",
    "superiorXp": 1700,
    "kph": 85,
    "kphSource": "money making guide: Killing basilisk knights (Slayer)",
    "kphNote": "rate is for Basilisk Knights"
  },
  {
    "name": "Wyrms",
    "slayerXp": 123,
    "hp": 120,
    "superior": "Shadow wyrm",
    "superiorXp": 3520,
    "kph": 150,
    "kphSource": "money making guide: Killing Wyrms (Slayer)",
    "kphNote": null
  },
  {
    "name": "Dust Devils",
    "slayerXp": 130,
    "hp": 130,
    "superior": "Choke devil",
    "superiorXp": 3000,
    "kph": 846,
    "kphSource": "Slayer training: 110,000 XP/h (Magic)",
    "kphNote": "derived from XP/h using Magic"
  },
  {
    "name": "Kurask",
    "slayerXp": 97,
    "hp": 97,
    "superior": "King kurask",
    "superiorXp": 2767.4,
    "kph": 180,
    "kphSource": "money making guide: Killing kurasks",
    "kphNote": null
  },
  {
    "name": "Venators",
    "slayerXp": 405,
    "hp": 345,
    "superior": "Blood-starved venator",
    "superiorXp": 3622.5,
    "kph": null,
    "kphSource": null,
    "kphNote": null
  },
  {
    "name": "Gargoyles",
    "slayerXp": 105,
    "hp": 105,
    "superior": "Marble gargoyle",
    "superiorXp": 2768,
    "kph": 230,
    "kphSource": "money making guide: Killing gargoyles",
    "kphNote": null
  },
  {
    "name": "Aquanites",
    "slayerXp": 180,
    "hp": 180,
    "superior": "Elder aquanite",
    "superiorXp": 4200,
    "kph": null,
    "kphSource": null,
    "kphNote": null
  },
  {
    "name": "Nechryael",
    "slayerXp": 105,
    "hp": 105,
    "superior": "Nechryarch",
    "superiorXp": 3280,
    "kph": 143,
    "kphSource": "money making guide: Picking up drops from Greater Nechryael",
    "kphNote": "rate is for Greater Nechryael"
  },
  {
    "name": "Drakes",
    "slayerXp": 230.6,
    "hp": 225,
    "superior": "Guardian Drake",
    "superiorXp": 7087,
    "kph": 90,
    "kphSource": "money making guide: Killing Drakes (Slayer)",
    "kphNote": null
  },
  {
    "name": "Abyssal Demons",
    "slayerXp": 150,
    "hp": 150,
    "superior": "Greater abyssal demon",
    "superiorXp": 4200,
    "kph": 533,
    "kphSource": "Slayer training: 80,000 XP/h (Magic)",
    "kphNote": "derived from XP/h using Magic"
  },
  {
    "name": "Dark Beasts",
    "slayerXp": 225.4,
    "hp": 220,
    "superior": "Night beast",
    "superiorXp": 6462,
    "kph": 186,
    "kphSource": "Slayer training: 42,000 XP/h",
    "kphNote": "derived from XP/h"
  },
  {
    "name": "Araxytes",
    "slayerXp": 100,
    "hp": 100,
    "superior": "Dreadborn Araxyte",
    "superiorXp": 4462.5,
    "kph": 1000,
    "kphSource": "Slayer training: 100,000 XP/h (Cannon and Venator bow)",
    "kphNote": "derived from XP/h using Cannon and Venator bow"
  },
  {
    "name": "Smoke Devils",
    "slayerXp": 185,
    "hp": 185,
    "superior": "Nuclear smoke devil",
    "superiorXp": 2400,
    "kph": 811,
    "kphSource": "Slayer training: 150,000 XP/h (Magic)",
    "kphNote": "derived from XP/h using Magic"
  },
  {
    "name": "Hydras",
    "slayerXp": 322.5,
    "hp": 300,
    "superior": "Colossal hydra",
    "superiorXp": 8625,
    "kph": 80,
    "kphSource": "money making guide: Killing hydras",
    "kphNote": null
  }
];
